name: Daily Stock Downloader

on:
  schedule:
    - cron: '30 07 * * *' # 每天 UTC 07:30 (台灣時間 15:30) 執行
  workflow_dispatch:      # 允許您手動在網頁上點擊執行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests pandas

      - name: Run Downloader
        run: python download_tw_close_prices.py --output-dir ./data
        env:
          # 在 GitHub Secrets 設定您的變數
          DATA_DIR: "./data" 

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git auto-commit
          git add .
          git commit -m "Update stock data"
          git push
